version: '3'

services:
  nginx:
    container_name: webgpu-nginx
    build: docker/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
    working_dir: /var/www/html/webgpu
    volumes:
      - ./:/var/www/html/webgpu

  nodejs:
      container_name: webgpu-nodejs
      build: docker/nodejs
      environment: 
        - CHOKIDAR_USEPOLLING=true
      volumes:
        - ./:/var/www/html/webgpu/
      stdin_open: true
      tty: true

  php:
    container_name: webgpu-php
    build: docker/php
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/webgpu
